#!/bin/bash

activate_env () {
    if [ -e "${PYENV}/bin/activate" ]; then
        [ -n "${VIRTUAL_ENV}" ] || {
            echo "Activating python env"
            source "${PYENV}/bin/activate"
        }
    else
        echo "No Python environment found, bootstrapping"
        build_env.sh
        source "${PYENV}/bin/activate"
    fi
}

[ -n "$GDAL_DATA" ] || {
    export GDAL_DATA=$(gdal-config --datadir)
}

[ -e "$HOME/.datacube_integration.conf" ] || {
    cp /conf/datacube_integration.conf "$HOME/.datacube_integration.conf"
}

case "${1:-}" in
    lab|notebook)
        cd /nb
        [ -z "$SHELL" ] || {
            export SHELL="$(which bash)"
        }
        activate_env
        exec jupyter "${1}" --ip=0.0.0.0 --port="${NB_PORT}" --no-browser
    ;;

    rebuild-env)
        echo "Will wipe out environment in 5 seconds"
        sleep 5
        find $PYENV/ -maxdepth 1 ! -path $PYENV/ -exec rm -rf {} \+
        echo "Building new environment"
        build_env.sh
        exit 0
    ;;

    check-code)
        activate_env
        cd /src/datacube-core
        exec ./check-code.sh integration_tests
        ;;

    "")
        ;;

    help)
        echo "Following commands are supported"
        echo "  check-code  -- run datacube tests"
        echo "  lab         -- launch jupyter lab"
        echo "  notebook    -- launch jupyter notebook"
        echo "  rebuild-env -- rebuild python environment"
        ;;
    *)
        activate_env
        exec $@
        ;;
esac
