#!/bin/bash


# If current work directory is not owned by root
#   1. Update odc user/group to have same UID,GID as work directory
#   2. Relaunch this script as odc user
[[ $UID -ne 0 ]] || {
    target_uid=$(stat -c '%u' .)
    target_gid=$(stat -c '%g' .)

    [[ $target_uid -eq 0 ]] || {

        # unless gid already matches update gid
        [[ $(id -g odc) -eq ${target_gid} ]] || {
            groupmod --gid ${target_gid} odc
            usermod --gid ${target_gid} odc
        }

        # unless uid already matches: change it and update HOME
        [[ $(id -u odc) -eq ${target_uid} ]] || {
            usermod --uid ${target_uid} odc
            chown -R odc:odc /home/odc/
        }

        exec sudo -u odc -E -H bash "$0" "$@"
    }
}

[[ $UID -ne 0 ]] || echo "WARNING: Running as root"

# point pip cache to /wk volume
export PIP_CACHE_DIR=/wk/.cache/pip

case "${1:-help}" in
    wheels|download|compile|new|extend|pkg-recompile|new_no_index|list-manylinux-wheels|help)
        exec env-build-tool $@
        ;;
    *)
        exec "$@"
        ;;
esac
